"""
app/llm/providers/gemini.py

Google Gemini LLM Provider integration.
"""
from __future__ import annotations

import logging
from typing import Any

import httpx

from llm.base import BaseLLMProvider, LLMField
from llm.registry import LLMRegistry

logger = logging.getLogger(__name__)


@LLMRegistry.register("gemini")
class GeminiProvider(BaseLLMProvider):
    PROVIDER_ID = "gemini"
    DISPLAY_NAME = "Google Gemini"
    FIELDS = [
        LLMField(
            key="api_key",
            label="Gemini API Key",
            field_type="password",
            required=True,
            placeholder="AIzaSy...",
            help_text="Google AI Studio API key.",
        ),
        LLMField(
            key="model_name",
            label="Model",
            field_type="select",
            default="gemini-2.5-flash-lite",
            options=[
                "gemini-2.5-flash-lite",
                "gemini-2.5-flash",
                "gemini-3.5-flash-lite",
                "gemini-3.5-flash",
                "gemini-flash-lite-latest",
                "gemini-flash-latest",
            ],
            help_text="Select Gemini model version.",
        ),
        LLMField(
            key="temperature",
            label="Temperature",
            field_type="number",
            default=0.2,
            placeholder="0.2",
            help_text="Controls randomness (0.0 to 1.0).",
        ),
    ]

    async def generate_response(
        self,
        prompt: str,
        system_instruction: str = "",
        config: dict[str, Any] = None,
        history: Optional[list[dict[str, str]]] = None,
    ) -> str:
        config = config or {}
        api_key = config.get("api_key") or ""
        if not api_key:
            raise ValueError("Gemini API key is missing in system settings")

        model_name = config.get("model_name") or "gemini-3.6-flash"
        try:
            temperature = float(config.get("temperature", 0.2))
        except (ValueError, TypeError):
            temperature = 0.2

        contents: list[dict[str, Any]] = []

        if history and isinstance(history, list):
            for item in history:
                if isinstance(item, dict):
                    role = item.get("role", "user")
                    gemini_role = "model" if role in ("assistant", "bot", "model") else "user"
                    txt = item.get("content", "")
                    if txt:
                        contents.append({
                            "role": gemini_role,
                            "parts": [{"text": txt}],
                        })

        contents.append({
            "role": "user",
            "parts": [{"text": prompt}],
        })

        body: dict[str, Any] = {
            "contents": contents,
            "generationConfig": {
                "temperature": temperature,
            },
        }

        if system_instruction:
            body["systemInstruction"] = {
                "parts": [{"text": system_instruction}]
            }

        async with httpx.AsyncClient(timeout=60.0) as client:
            # Try requested model, with fallbacks if 404
            models_to_try = [model_name]
            for fallback in ["gemini-2.5-flash-lite", "gemini-2.5-flash", "gemini-3.5-flash-lite", "gemini-3.5-flash", "gemini-flash-lite-latest", "gemini-flash-latest"]:
                if fallback not in models_to_try:
                    models_to_try.append(fallback)

            last_resp = None
            data = None
            for m in models_to_try:
                clean_m = m.replace("models/", "")
                url = f"https://generativelanguage.googleapis.com/v1beta/models/{clean_m}:generateContent?key={api_key}"
                resp = await client.post(url, json=body)
                last_resp = resp
                if resp.status_code == 200:
                    data = resp.json()
                    break
                elif resp.status_code == 404:
                    logger.warning(f"Gemini model '{clean_m}' returned 404. Trying fallback...")
                    continue
                else:
                    logger.error(f"Gemini API error ({resp.status_code}): {resp.text}")
                    raise RuntimeError(f"Gemini API returned error HTTP {resp.status_code}: {resp.text}")

            if not data:
                logger.error(f"Gemini API error ({last_resp.status_code}): {last_resp.text}")
                raise RuntimeError(f"Gemini API returned error HTTP {last_resp.status_code}: {last_resp.text}")

        try:
            candidates = data.get("candidates", [])
            if not candidates:
                return "No response generated by Gemini."
            parts = candidates[0].get("content", {}).get("parts", [])
            text_outputs = [p.get("text", "") for p in parts if "text" in p]
            return "\n".join(text_outputs).strip() or "No text content returned."
        except Exception as err:
            logger.error(f"Error parsing Gemini response: {err}")
            raise RuntimeError(f"Failed to parse Gemini response: {err}")
