"""
app/llm/providers/ollama.py

Ollama & OpenAI-Compatible Local LLM Provider integration.
"""
from __future__ import annotations

import logging
from typing import Any, Optional

import httpx

from llm.base import BaseLLMProvider, LLMField
from llm.registry import LLMRegistry

logger = logging.getLogger(__name__)


@LLMRegistry.register("ollama")
class OllamaProvider(BaseLLMProvider):
    PROVIDER_ID = "ollama"
    DISPLAY_NAME = "Ollama / Local Custom LLM"
    FIELDS = [
        LLMField(
            key="base_url",
            label="Base URL",
            field_type="text",
            required=True,
            default="http://localhost:11434",
            placeholder="http://localhost:11434",
            help_text="URL of local Ollama or OpenAI-compatible server.",
        ),
        LLMField(
            key="model_name",
            label="Model Name",
            field_type="text",
            required=True,
            default="llama3.2",
            placeholder="llama3.2 / mistral / qwen2.5",
            help_text="Ollama or local model name.",
        ),
        LLMField(
            key="api_key",
            label="API Key (Optional)",
            field_type="password",
            required=False,
            default="",
            placeholder="Optional bearer token",
            help_text="Optional authorization key if required by your endpoint.",
        ),
        LLMField(
            key="temperature",
            label="Temperature",
            field_type="number",
            default=0.2,
            placeholder="0.2",
            help_text="Controls randomness (0.0 to 1.0).",
        ),
    ]

    async def generate_response(
        self,
        prompt: str,
        system_instruction: str = "",
        config: dict[str, Any] = None,
        history: Optional[list[dict[str, str]]] = None,
    ) -> str:
        config = config or {}
        base_url = (config.get("base_url") or "http://localhost:11434").rstrip("/")
        model_name = config.get("model_name") or "llama3.2"
        api_key = config.get("api_key") or ""
        try:
            temperature = float(config.get("temperature", 0.2))
        except (ValueError, TypeError):
            temperature = 0.2

        messages = []
        if system_instruction:
            messages.append({"role": "system", "content": system_instruction})

        if history and isinstance(history, list):
            for item in history:
                if isinstance(item, dict):
                    role = item.get("role", "user")
                    o_role = "assistant" if role in ("assistant", "bot", "model") else "user"
                    txt = item.get("content", "")
                    if txt:
                        messages.append({"role": o_role, "content": txt})

        messages.append({"role": "user", "content": prompt})

        headers = {"Content-Type": "application/json"}
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        body = {
            "model": model_name,
            "messages": messages,
            "temperature": temperature,
            "stream": False,
        }

        url = f"{base_url}/v1/chat/completions"

        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(url, headers=headers, json=body)
            if resp.status_code != 200:
                logger.error(f"Ollama/Local LLM API error ({resp.status_code}): {resp.text}")
                raise RuntimeError(f"Ollama/Local LLM returned HTTP {resp.status_code}: {resp.text}")
            data = resp.json()

        try:
            choices = data.get("choices", [])
            if not choices:
                return "No response generated by local LLM."
            return choices[0].get("message", {}).get("content", "").strip() or "No content returned."
        except Exception as err:
            logger.error(f"Error parsing local LLM response: {err}")
            raise RuntimeError(f"Failed to parse local LLM response: {err}")
