"""
app/llm/providers/openai.py

OpenAI LLM Provider integration.
"""
from __future__ import annotations

import logging
from typing import Any, Optional

import httpx

from llm.base import BaseLLMProvider, LLMField
from llm.registry import LLMRegistry

logger = logging.getLogger(__name__)


@LLMRegistry.register("openai")
class OpenAIProvider(BaseLLMProvider):
    PROVIDER_ID = "openai"
    DISPLAY_NAME = "OpenAI (ChatGPT)"
    FIELDS = [
        LLMField(
            key="api_key",
            label="OpenAI API Key",
            field_type="password",
            required=True,
            placeholder="sk-proj-...",
            help_text="OpenAI API secret key.",
        ),
        LLMField(
            key="model_name",
            label="Model",
            field_type="select",
            default="gpt-4o-mini",
            options=["gpt-4o-mini", "gpt-4o", "gpt-4-turbo", "o3-mini"],
            help_text="Select OpenAI model.",
        ),
        LLMField(
            key="temperature",
            label="Temperature",
            field_type="number",
            default=0.2,
            placeholder="0.2",
            help_text="Controls randomness (0.0 to 1.0).",
        ),
    ]

    async def generate_response(
        self,
        prompt: str,
        system_instruction: str = "",
        config: dict[str, Any] = None,
        history: Optional[list[dict[str, str]]] = None,
    ) -> str:
        config = config or {}
        api_key = config.get("api_key") or ""
        if not api_key:
            raise ValueError("OpenAI API key is missing in system settings")

        model_name = config.get("model_name") or "gpt-4o-mini"
        try:
            temperature = float(config.get("temperature", 0.2))
        except (ValueError, TypeError):
            temperature = 0.2

        messages = []
        if system_instruction:
            messages.append({"role": "system", "content": system_instruction})

        if history and isinstance(history, list):
            for item in history:
                if isinstance(item, dict):
                    role = item.get("role", "user")
                    o_role = "assistant" if role in ("assistant", "bot", "model") else "user"
                    txt = item.get("content", "")
                    if txt:
                        messages.append({"role": o_role, "content": txt})

        messages.append({"role": "user", "content": prompt})

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        body = {
            "model": model_name,
            "messages": messages,
            "temperature": temperature,
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post("https://api.openai.com/v1/chat/completions", headers=headers, json=body)
            if resp.status_code != 200:
                logger.error(f"OpenAI API error ({resp.status_code}): {resp.text}")
                raise RuntimeError(f"OpenAI API returned HTTP {resp.status_code}: {resp.text}")
            data = resp.json()

        try:
            choices = data.get("choices", [])
            if not choices:
                return "No response generated by OpenAI."
            return choices[0].get("message", {}).get("content", "").strip() or "No content returned."
        except Exception as err:
            logger.error(f"Error parsing OpenAI response: {err}")
            raise RuntimeError(f"Failed to parse OpenAI response: {err}")
