"""
app/integrations/google_findmy.py

Google Find My Device / Find Hub integration.

Authentication:
  Requires a secrets.json file generated by the GoogleFindMyTools script:
  https://github.com/leonboe1/GoogleFindMyTools

  The entire contents of secrets.json must be pasted into the credential field.
  The file contains OAuth refresh tokens and E2EE owner keys for decryption.

API:
  Google's internal Nova API (protobuf over HTTPS).
  Token endpoint: https://oauth2.googleapis.com/token
  Nova endpoint:  https://android.googleapis.com/nova_android_backend/...

Decryption:
  Device locations are E2EE encrypted with AES-256-GCM using per-device owner
  keys stored in secrets.json. Decryption is done locally in Python.
"""
from __future__ import annotations

import base64
import json
import logging
import struct
from datetime import datetime, timezone, timedelta
from typing import AsyncIterator, Optional  # Optional kept for _parse_timestamp / _decrypt_location

import httpx

from integrations.base import (
    BaseIntegration, AuthContext, AuthExpiredError,
    IntegrationField, RemoteDevice,
)
from integrations.registry import IntegrationRegistry
from models.schemas import NormalizedPosition

logger = logging.getLogger(__name__)

_CLIENT_SIG = "38918a453d07199354f8b19af05ec6562ced5788"
_BUNDLE_ID  = "com.google.android.apps.adm"

# Per-account in-memory cursor: last fetch timestamp
_last_seen: dict[tuple, datetime] = {}


@IntegrationRegistry.register("google_findmy")
class GoogleFindMyIntegration(BaseIntegration):

    PROVIDER_ID                  = "google_findmy"
    DISPLAY_NAME                 = "Google Find My"
    POLL_INTERVAL_SECONDS        = 300   # 5 min — Google rate-limits aggressively
    POLL_INTERVAL_ACTIVE_SECONDS = 120   # 2 min when active

    FIELDS = [
        IntegrationField(
            key="secrets_json",
            label="secrets.json",
            field_type="textarea",
            required=True,
            placeholder='{"username": "you@gmail.com", "aas_token": "…", "android_id": "…", "devices": […]}',
            help_text=(
                "Paste the full contents of the secrets.json file generated by GoogleFindMyTools "
                "(github.com/leonboe1/GoogleFindMyTools). "
                "Run the tool on any machine that has Google Chrome, then copy the output here."
            ),
        ),
    ]

    # ── Auth ──────────────────────────────────────────────────────────────────

    async def authenticate(self, credentials: dict) -> AuthContext:
        raw = credentials.get("secrets_json", "")
        try:
            secrets = json.loads(raw)
        except json.JSONDecodeError as e:
            raise ValueError(f"Google Find My: secrets_json is not valid JSON: {e}")

        if not secrets.get("aas_token"):
            raise ValueError(
                "Google Find My: secrets_json must contain an aas_token. "
                "Generate it with GoogleFindMyTools (github.com/leonboe1/GoogleFindMyTools)."
            )

        return await self._authenticate_aas(secrets)

    async def _authenticate_aas(self, secrets: dict) -> AuthContext:
        import gpsoauth

        username  = secrets.get("username") or secrets.get("email") or ""
        aas_token = secrets["aas_token"]

        # android_id may be top-level or nested under fcm_credentials.gcm
        android_id = (
            secrets.get("android_id")
            or (secrets.get("fcm_credentials") or {}).get("gcm", {}).get("android_id")
            or ""
        )
        android_id = str(android_id)
        owner_keys = self._extract_owner_keys(secrets)

        if not android_id:
            raise ValueError("Google Find My: no android_id in secrets.json.")

        adm_resp = gpsoauth.perform_oauth(
            username, aas_token, android_id,
            service="oauth2:https://www.googleapis.com/auth/android_device_manager",
            app=_BUNDLE_ID,
            client_sig=_CLIENT_SIG,
        )
        access_token = adm_resp.get("Auth")
        if not access_token:
            raise AuthExpiredError(f"Google Find My: AAS token exchange failed: {adm_resp}")

        logger.info("Google Find My: authenticated as %s (AAS legacy)", username)

        return AuthContext(
            data={
                "username":     username,
                "access_token": access_token,
                "owner_keys":   owner_keys,
                "secrets":      secrets,
            },
            token_expires_at=datetime.now(timezone.utc) + timedelta(seconds=3500),
        )

    # ── List devices ──────────────────────────────────────────────────────────

    async def list_remote_devices(self, auth_ctx: AuthContext) -> list[RemoteDevice]:
        try:
            devices_raw = await self._fetch_device_list(auth_ctx)
        except Exception as e:
            logger.error(f"Google Find My: list_remote_devices error: {e}", exc_info=True)
            return []

        result = []
        for d in devices_raw:
            # ADM API uses resourceId; Nova/BLE trackers use canonicId
            canonic_id = (
                d.get("resourceId") or d.get("canonicId")
                or d.get("id") or d.get("deviceId") or ""
            )
            name = (
                d.get("friendlyName") or d.get("name")
                or d.get("deviceName") or d.get("model") or canonic_id
            )
            if not canonic_id:
                logger.debug("Google Find My: skipping device with no ID: %s", list(d.keys()))
                continue
            result.append(RemoteDevice(
                remote_id=canonic_id,
                name=name,
                imei=None,  # Find My doesn't expose IMEI
            ))
        return result

    # ── Fetch positions ───────────────────────────────────────────────────────

    async def fetch_positions(
        self,
        auth_ctx: AuthContext,
        devices: list[dict],
    ) -> AsyncIterator[NormalizedPosition]:
        if not devices:
            return

        access_token = auth_ctx.data["access_token"]
        owner_keys   = auth_ctx.data["owner_keys"]
        account_key  = auth_ctx.data["username"]

        for device in devices:
            canonic_id = device.get("remote_id", "")
            imei       = device.get("imei", "")
            if not canonic_id:
                continue

            try:
                location = await self._fetch_device_location(
                    access_token, canonic_id, owner_keys
                )
            except AuthExpiredError:
                raise
            except Exception as e:
                logger.warning(f"Google Find My: location fetch failed for {canonic_id}: {e}")
                continue

            if not location:
                continue

            device_time = location.get("timestamp")
            if not device_time:
                continue

            # Deduplicate
            device_key = (account_key, canonic_id)
            last_seen  = _last_seen.get(device_key)
            if last_seen is not None and device_time <= last_seen:
                logger.debug(f"Google Find My: skipping duplicate for {canonic_id} at {device_time}")
                continue
            _last_seen[device_key] = device_time

            lat      = location.get("latitude")
            lng      = location.get("longitude")
            accuracy = location.get("accuracy")

            if lat is None or lng is None:
                continue

            sensors: dict = {}
            if accuracy is not None:
                sensors["accuracy_m"] = accuracy
            battery = location.get("battery_level")
            if battery is not None:
                sensors["battery.level"] = battery
            source = location.get("source")
            if source:
                sensors["location_source"] = source

            yield NormalizedPosition(
                imei=imei,
                device_time=device_time,
                server_time=datetime.now(timezone.utc),
                latitude=lat,
                longitude=lng,
                altitude=None,
                speed=None,
                course=None,
                satellites=None,
                ignition=None,   # Find My trackers don't report ignition
                sensors=sensors,
                raw_data={"source": "google_findmy", "canonic_id": canonic_id},
            )

    # ── Credentials test ──────────────────────────────────────────────────────

    async def test_credentials(self, credentials: dict) -> tuple[bool, str]:
        try:
            ctx = await self.authenticate(credentials)
            key_count = len(ctx.data["owner_keys"])
            devices   = await self.list_remote_devices(ctx)
            return True, (
                f"Connected as {ctx.data['username']} — "
                f"{key_count} owner key(s), {len(devices)} device(s) visible."
            )
        except Exception as e:
            return False, str(e)

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _extract_owner_keys(self, secrets: dict) -> dict[str, bytes]:
        """
        Build a mapping of { canonic_id → raw_key_bytes } from secrets.json.
        Keys are used to decrypt AES-GCM encrypted location payloads.
        """
        result: dict[str, bytes] = {}
        devices = (
            secrets.get("devices")
            or secrets.get("device_keys")
            or []
        )
        if isinstance(devices, dict):
            devices = list(devices.values())

        for d in devices:
            cid = d.get("canonicId") or d.get("canonic_id") or d.get("id") or ""
            if not cid:
                continue

            # Key may be base64 or hex encoded
            raw_key = (
                d.get("ownerKey")
                or d.get("owner_key")
                or d.get("key")
                or d.get("encryptionKey")
                or ""
            )
            if not raw_key:
                continue

            try:
                key_bytes = base64.b64decode(raw_key)
                result[cid] = key_bytes
            except Exception:
                try:
                    key_bytes = bytes.fromhex(raw_key)
                    result[cid] = key_bytes
                except Exception:
                    logger.warning(f"Google Find My: could not decode key for device {cid}")

        return result

    async def _fetch_device_list(self, auth_ctx: AuthContext) -> list[dict]:
        """
        Return BLE tracker devices embedded in secrets.json.

        Google's Find My Device API for Android phones is not publicly accessible
        (it uses internal session-authenticated endpoints).  Only BLE trackers
        registered on the Find My Device network appear here, via the device list
        that GoogleFindMyTools writes into secrets.json.
        """
        secrets = auth_ctx.data["secrets"]
        devices = secrets.get("devices") or secrets.get("device_keys") or []
        if isinstance(devices, dict):
            devices = list(devices.values())
        return devices

    async def _fetch_device_location(
        self,
        access_token: str,
        canonic_id: str,
        owner_keys: dict[str, bytes],
    ) -> Optional[dict]:
        """
        Request the location of a single device via the Android Device Manager API.
        Android phones return plaintext locations; BLE trackers need E2EE decryption.
        """
        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type":  "application/json",
        }

        # Location retrieval for BLE trackers requires the owner key for decryption.
        # Without it there is nothing we can do for this device.
        owner_key = owner_keys.get(canonic_id)
        if not owner_key:
            logger.debug(
                "Google Find My: no owner key for %s — device may be an Android phone "
                "(not supported via this API) or key is missing from secrets.json",
                canonic_id,
            )
            return None

        # BLE trackers: fetch the encrypted location report and decrypt it.
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                "https://android.googleapis.com/nova_android_backend/v1/locate_tracker",
                headers=headers,
                json={"canonicId": canonic_id},
            )

        if resp.status_code == 401:
            raise AuthExpiredError("Google Find My: access token rejected")
        if resp.status_code not in (200, 201):
            logger.warning(
                "Google Find My: locate_tracker returned %s for %s — %s",
                resp.status_code, canonic_id, resp.text[:200],
            )
            return None

        data = resp.json()
        logger.debug("Google Find My: tracker location keys for %s: %s", canonic_id, list(data.keys()))
        return self._parse_location_response(data, owner_key, canonic_id)

    def _parse_location_response(
        self,
        data: dict,
        owner_key: Optional[bytes],
        canonic_id: str,
    ) -> Optional[dict]:
        """
        Parse and decrypt a location response.
        Handles both plaintext locations (Android devices) and
        encrypted locations (Find My trackers).
        """
        # Plaintext location (Android phones with Find My Device enabled)
        loc = data.get("location") or data.get("lastKnownLocation")
        if loc:
            lat  = loc.get("latitude")  or loc.get("lat")
            lng  = loc.get("longitude") or loc.get("lng")
            acc  = loc.get("accuracyMeters") or loc.get("accuracy")
            ts_ms = loc.get("createTime") or loc.get("timestamp") or loc.get("timestampMs")

            if lat is not None and lng is not None:
                return {
                    "latitude":      float(lat),
                    "longitude":     float(lng),
                    "accuracy":      float(acc) if acc else None,
                    "timestamp":     self._parse_timestamp(ts_ms),
                    "battery_level": data.get("batteryLevel"),
                    "source":        "android",
                }

        # Encrypted location blob (Find My trackers)
        encrypted_blob = (
            data.get("encryptedLocation")
            or data.get("encryptedReports")
            or data.get("locationReport")
        )
        if encrypted_blob:
            return self._decrypt_location(encrypted_blob, owner_key, canonic_id)

        logger.debug(f"Google Find My: no location data in response for {canonic_id}: {list(data.keys())}")
        return None

    def _decrypt_location(
        self,
        encrypted_blob,
        owner_key: bytes,
        canonic_id: str,
    ) -> Optional[dict]:
        """
        Decrypt an AES-256-GCM encrypted location report using the device's owner key.
        Based on the decryption logic in GoogleFindMyTools/NovaApi/ExecuteAction/LocateTracker/decrypt_locations.py
        """
        try:
            from cryptography.hazmat.primitives.ciphers.aead import AESGCM
            from cryptography.hazmat.primitives import hashes
            from cryptography.hazmat.primitives.kdf.hkdf import HKDF
            from cryptography.hazmat.backends import default_backend

            # Handle both list and single blob
            reports = encrypted_blob if isinstance(encrypted_blob, list) else [encrypted_blob]

            best: Optional[dict] = None
            best_ts = datetime.min.replace(tzinfo=timezone.utc)

            for report in reports:
                try:
                    # Extract the raw encrypted bytes
                    if isinstance(report, str):
                        payload = base64.b64decode(report)
                    elif isinstance(report, dict):
                        raw = report.get("encryptedBytes") or report.get("data") or report.get("payload") or ""
                        if not raw:
                            continue
                        payload = base64.b64decode(raw) if isinstance(raw, str) else bytes(raw)
                    else:
                        continue

                    # Location report format (from GoogleFindMyTools decrypt_locations.py):
                    # Byte 0:     status byte
                    # Bytes 1-4:  timestamp (big-endian uint32, seconds since Jan 1 2001)
                    # Bytes 5-8:  centiseconds (unused)
                    # Bytes 9-12: encrypted latitude offset
                    # Bytes 13-16: encrypted longitude offset
                    # Remaining: nonce + ciphertext + tag

                    if len(payload) < 20:
                        continue

                    # The Find My Device network uses a simplified report format
                    # where the key is used directly (not ECDH like Apple's network)
                    # We derive an AES key from the owner key using HKDF
                    hkdf = HKDF(
                        algorithm=hashes.SHA256(),
                        length=32,
                        salt=None,
                        info=b"find_my_device_location",
                        backend=default_backend(),
                    )
                    aes_key = hkdf.derive(owner_key)

                    # Nonce is typically the first 12 bytes of the payload
                    nonce      = payload[:12]
                    ciphertext = payload[12:]

                    aesgcm    = AESGCM(aes_key)
                    plaintext = aesgcm.decrypt(nonce, ciphertext, None)

                    # Parse the decrypted plaintext
                    # Format: 4-byte timestamp | 4-byte lat_int | 4-byte lng_int | 1-byte accuracy_exp
                    if len(plaintext) < 9:
                        continue

                    ts_raw  = struct.unpack(">I", plaintext[0:4])[0]
                    lat_int = struct.unpack(">i", plaintext[4:8])[0]  # signed
                    lng_int = struct.unpack(">i", plaintext[8:12])[0] if len(plaintext) >= 12 else 0
                    acc_exp = plaintext[12] if len(plaintext) > 12 else 0

                    # Timestamp: seconds since Jan 1, 2001 (Apple/Google network epoch)
                    EPOCH_OFFSET = 978307200  # seconds between 1970 and 2001
                    ts = datetime.fromtimestamp(ts_raw + EPOCH_OFFSET, tz=timezone.utc)

                    # Coordinates: divide by 10^7 to get degrees
                    lat = lat_int / 1e7
                    lng = lng_int / 1e7

                    # Accuracy: 10^acc_exp metres
                    accuracy = 10 ** acc_exp if acc_exp < 10 else None

                    location = {
                        "latitude":  lat,
                        "longitude": lng,
                        "accuracy":  accuracy,
                        "timestamp": ts,
                        "source":    "findmy_encrypted",
                    }

                    if ts > best_ts:
                        best_ts = ts
                        best = location

                except Exception as e:
                    logger.debug(f"Google Find My: failed to decrypt one report for {canonic_id}: {e}")
                    continue

            return best

        except ImportError:
            logger.error(
                "Google Find My: 'cryptography' package is required. "
                "Install it with: pip install cryptography"
            )
            return None
        except Exception as e:
            logger.error(f"Google Find My: decryption error for {canonic_id}: {e}", exc_info=True)
            return None

    def _parse_timestamp(self, ts) -> Optional[datetime]:
        """Parse various timestamp formats into a timezone-aware datetime."""
        if ts is None:
            return None
        try:
            if isinstance(ts, str):
                # RFC3339 or ISO format
                return datetime.fromisoformat(ts.replace("Z", "+00:00"))
            val = float(ts)
            # Detect milliseconds vs seconds
            if val > 1e11:
                val /= 1000
            return datetime.fromtimestamp(val, tz=timezone.utc)
        except Exception:
            return None
